#!/bin/bash
# Motley module for machine aliases
motley_defmodule machine_alias <<'EOF'
Machine aliasing
Allows you to define alternative names (in Motley's terms) and hostname/IP
references for machines:

  machine foo alias bar                 # foo is a machine with two hostnames
  machine foo alias bar=192.168.0.24    # "bar" is a motley-mnemonic for the IP

Aliases behave in two ways:

  foo docker ...                        # address foo directly
  bar docker ...                        # address foo using 192.168.0.24
  ssh $bar ...                          # $bar = 192.168.0.24
EOF

motley_machine_meta_alias() {
  local machine_key=$1
  local machine=$2
  local alias=$3
  local aname=${alias%%=*}
  local ahost=${alias#*=}

  eval "MOTLEY_MACHINE_${machine_key}_ALIASES=\"\$MOTLEY_MACHINE_${machine_key}_ALIASES \$aname\""
  eval "$aname=\$ahost"
  eval "$aname() { $machine_key \"\$@\"; }"
}
