#!/bin/bash
# https://github.com/spencertipping/motley
# MIT license

MOTLEY_MODES=
MOTLEY_COMMANDS=
MOTLEY_MODULES=
MOTLEY_MACHINES=

MOTLEY_SELF=$(hostname)

# Core functions
motley_defmodule() {
  MOTLEY_MODULES="$MOTLEY_MODULES $1"
  eval "MOTLEY_MODULE_DOC_$1=\"\$(cat)\""
}

motley_defmode() {
  for m; do
    if [[ "${MOTLEY_MODES/ $m /}" = "$MOTLEY_MODES" ]]; then
      MOTLEY_MODES="$MOTLEY_MODES $m "
      eval "motley_${m}_init() { :; }
            motley_${m}_end()  { :; }
            motley_${m}_machine() {
              local machine_key=\$1
              local machine=\$2
              local cmd=\$3
              shift 3
              motley_\${cmd}_all  \"\$machine_key\" \"\$machine\" '$m' \"\$@\"
              motley_\${cmd}_${m} \"\$machine_key\" \"\$machine\"      \"\$@\"
            }"

      for c in $MOTLEY_COMMANDS; do
        eval "motley_${c}_init_${m}() { :; }
              motley_${c}_${m}()      { :; }
              motley_${c}_end_${m}()  { :; }"
      done
    fi
  done
}

# Machine definition function
machine() {
  local machine=$1
  local machine_key=${machine//[^A-Za-z0-9]/_}
  shift

  MOTLEY_MACHINES="$MOTLEY_MACHINES $machine"
  eval "$machine_key() {
    motley_\${MOTLEY_MODE}_machine \"$machine_key\" \"$machine\" \"\$@\"
  }"

  while (( $# )); do
    motley_machine_meta_$1 "$machine_key" "$machine" "$2"
    shift 2
  done
}

motley_machine_origin() {
  local origin=$1
  while eval "[[ -n \$MOTLEY_MACHINE_ORIGIN_${origin//[^A-Za-z0-9]/_} ]]"; do
    eval "origin=\$MOTLEY_MACHINE_ORIGIN_${origin//[^A-Za-z0-9]/_}"
  done
  echo "$origin"
}

motley_machine_set_origin() {
  eval "MOTLEY_MACHINE_ORIGIN_${1//[^A-Za-z0-9]/_}=\$2"
}

# Informational modes (these bypass the Motfile)
motley_defmode modes modules

motley_modes_init() {
  echo "available modes:"
  for m in $MOTLEY_MODES; do
    echo "- $m"
  done
  exit 0
}

motley_modules_init() {
  echo "available modules:"
  for m in $MOTLEY_MODULES; do
    echo "- $m"
  done
  exit 0
}

# Core operative modes
motley_defmode machines ls

motley_machines_end() {
  for m in $MOTLEY_MACHINES; do
    echo $m
  done
}

motley_ls_machine() {
  local machine_key=$1
  shift
  echo "$@"
  local machine=$1
  local cmd=$2
  shift 2
  motley_${cmd}_all "$machine_key" "$machine" '$m' "$@"
}

# Command definitions
motley_defcommand() {
  for c; do
    MOTLEY_COMMANDS="$MOTLEY_COMMANDS $c"
    for m in $MOTLEY_MODES; do
      eval "motley_${c}_all()       { :; }
            motley_${c}_init_all()  { :; }
            motley_${c}_end_all()   { :; }
            motley_${c}_init_${m}() { :; }
            motley_${c}_${m}()      { :; }
            motley_${c}_end_${m}()  { :; }"
    done
  done
}

# Machine application
# A lot of motley modes will predicate on machines and let you specify them on
# the command line as arguments. To simplify the logic involved, we provide a
# function 'motley_machine_applies' that works like this:
#
#   if motley_machine_applies foo "${MOTLEY_ARGS[@]}"; then
#     echo you selected foo
#   fi

MOTLEY_MACHINE_APPLIES_IF=
motley_machine_applies_if() {
  MOTLEY_MACHINE_APPLIES_IF="$MOTLEY_MACHINE_APPLIES_IF $*"
}

motley_machine_applies() {
  # It obviously applies if it's in the arguments list.
  local m=$1
  shift
  for a; do
    [[ "$m" = "$a" ]] && return 0
  done
  for f in $MOTLEY_MACHINE_APPLIES_IF; do
    $f "$m" "$@" && return 0
  done
  return 1
}

# Main argument processing
# First load any motley modules.
for m in "$(dirname "$0")"/motley-* ~/.motley.d/motley-*; do
  [[ -r "$m" ]] && source "$m"
done

# Now decide which motfile we're using and cd there.
MOTLEY_MOTFILE=Motfile
while [[ ${1#-} != $1 ]]; do
  case $1 in
    -f)
      MOTLEY_MOTFILE=$2
      shift 2
      ;;

    # Help about a module or general usage
    -h)
      if [[ -n "$2" ]]; then
        {
          eval "echo \"\$MOTLEY_MODULE_DOC_$2\""
          echo
        } >&2
      else
        {
          echo "motley usage:"
          echo "  motley [-f /path/to/Motfile] mode [args...]"
          echo "  motley -h [topic]"
          echo
          echo "where modes are"
          for m in $MOTLEY_MODES; do
            echo "- $m"
          done
          echo
          echo "help topics (motley -h topic):"
          for m in $MOTLEY_MODULES; do
            echo "- $m"
          done | sort
          echo
        } >&2
      fi
      exit 0
      ;;

    *)
      echo "motley: unrecognized option $1 (try -h for help)" 1>&2
      exit 1
      ;;
  esac
done

cd "$(dirname "$MOTLEY_MOTFILE")"
MOTLEY_MOTFILE=$(basename "$MOTLEY_MOTFILE")

# Load any more modules in the motfile directory.
for m in motley-*; do
  [[ -r "$m" ]] && source "$m"
done

# Now set the mode based on command-line arguments, initialize modes, source
# the motfile, and end modes.
MOTLEY_MODE=${1:-ls}
shift
MOTLEY_ARGS=( "$@" )

motley_${MOTLEY_MODE}_init
for c in $MOTLEY_COMMANDS; do
  motley_${c}_init_all
  motley_${c}_init_${MOTLEY_MODE}
done

if [[ -r "$MOTLEY_MOTFILE" ]]; then
  source "$MOTLEY_MOTFILE"
else
  echo "motley: no Motfile present (try motley -h for help)" >&2
fi

motley_${MOTLEY_MODE}_end
for c in $MOTLEY_COMMANDS; do
  motley_${c}_end_all
  motley_${c}_end_${MOTLEY_MODE}
done
