#!/bin/bash
# Motley sh command
motley_defmodule sh <<'EOF'
sh command
Runs a shell command on the addressed machine. For example:

  machine foo
  foo sh 'echo hi'
EOF

motley_defcommand sh

motley_sh_conf() {
  local machine_key=$1
  local machine=$2
  shift 2
  [[ $MOTLEY_SELF = $machine ]] && eval "$@"
}
