#!/bin/bash
# https://github.com/spencertipping/motley
# MIT license

MOTLEY_MODES=
MOTLEY_MODULES=
MOTLEY_HOSTS=

# Core functions
# These are all defined with the motley_ prefix, then exported later by
# modules.
motley_host() {
  local h=$1
  shift
  MOTLEY_HOSTS="$MOTLEY_HOSTS $h"
  eval "$h() {"'
    motley_${MOTLEY_MODE}_host "$@"
  }'"
  MOTLEY_HOST_${h//[^a-zA-Z0-9]/_}=( \"\$@\" )"
}

motley_defmode() {
  for m; do
    MOTLEY_MODES="$MOTLEY_MODES $m"
    eval "motley_${m}_init() { :; }
          motley_${m}_host() { :; }
          motley_${m}_end()  { :; }"
  done
}

motley_splitmode() {
  for m; do
    motley_defmode $m
    eval "motley_${m}_host() {"'
      if [[ `hostname` = $1 ]]; then
        local cmd=$2
        shift 2
        motley_${MOTLEY_MODE}_self "$cmd" "$@"
      else
        local hostname=$1
        local cmd=$2
        shift 2
        motley_${MOTLEY_MODE}_other "$cmd" "$hostname" "$@"
      fi
    }'
  done
}

# Informational modes
motley_defmode modes modules hosts

motley_modes_init() {
  for m in $MOTLEY_MODES; do
    echo $m
  done
  exit 0
}

motley_modules_init() {
  for m in $MOTLEY_MODULES; do
    echo $m
  done
  exit 0
}

motley_hosts_end() {
  for h in $MOTLEY_HOSTS; do
    eval "echo \$h \"\${MOTLEY_HOST_${m//[^a-zA-Z0-9]/_}[@]}\""
  done
  exit 0
}

# Core operative modes
motley_defmode ls

motley_ls_each() {
  if (( ${#MOTLEY_ARGS} > 0 )); then
    local echo_this_one=
    for arg in "${MOTLEY_ARGS[@]}"; do
      if [[ "$arg" = "$1" ]]; then
        echo_this_one=yes
        break
      fi
    done

    if [[ -n "$echo_this_one" ]]; then
      echo "$@"
    fi
  else
    echo "$@"
  fi
}

# Main argument processing
# First load any motley modules.
for m in "$(dirname "$0")"/motley-* ~/.motley.d/*; do
  [[ -f "$m" ]] && source "$m"
done

# Now decide which motfile we're using and cd there.
MOTLEY_MOTFILE=Motfile
while [[ ${1#-} != $1 ]]; do
  case $1 in
    -f)
      MOTLEY_MOTFILE=$2
      shift 2
      ;;

    -h)
      motley_usage
      exit 0
      ;;

    *)
      echo "motley: unrecognized option $1 (try -h for help)" 1>&2
      exit 1
      ;;
  esac
done

cd "$(dirname "$MOTLEY_MOTFILE")"
