#!/bin/bash
# Motley module for machine aliases
motley_defmodule machine_alias <<'EOF'
Machine aliasing
Allows you to define alternative names (in Motley's terms) and hostname/IP
references for machines:

  machine foo alias bar                 # foo is a machine with two hostnames
  machine foo alias bar=192.168.0.24    # "bar" is a motley-mnemonic for the IP

Aliases behave in two ways:

  foo docker ...                        # address foo directly
  bar docker ...                        # address foo using 192.168.0.24
  ssh $bar ...                          # $bar = 192.168.0.24
EOF

motley_machine_applies_if motley_machine_alias_matches

motley_machine_alias_matches() {
  local machine=$1
  shift
  for machine_or_alias; do
    eval "local amachine=\$MOTLEY_ALIAS_$machine_or_alias"
    [[ "$amachine" = "$machine" ]] && return 0
  done
  return 1
}

motley_machine_meta_alias() {
  local machine_key=$1
  local machine=$2
  local alias=$3
  local aname=${alias%%=*}
  local ahost=${alias#*=}

  if [[ "${alias/=/}" != "$alias" ]]; then
    motley_machine_set_origin "$aname" "$ahost"
  else
    motley_machine_set_origin "$aname" "$machine"
  fi

  eval "MOTLEY_MACHINE_${machine_key}_ALIASES=\"\$MOTLEY_MACHINE_${machine_key}_ALIASES \$aname\""
  eval "MOTLEY_ALIAS_$aname=\$machine"
  eval "$aname=\$ahost"
  machine $aname
}
